url: "qichensong.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Qichen Song" # the name of your site, e.g. ACME Corp.
description: "HQI Postdoctoral Fellow, Harvard University"
